// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH-oit5RpFkNWADB6MMmQZuZhh-gUq44E',
    appId: '1:100144255999:web:020efc5b187da67104cdca',
    messagingSenderId: '100144255999',
    projectId: 'justifind-9fda1',
    authDomain: 'justifind-9fda1.firebaseapp.com',
    storageBucket: 'justifind-9fda1.firebasestorage.app',
    measurementId: 'G-KG9YYF3LWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPpHUQz5htiRhTRe_uFWB6hhQbwyVjy8E',
    appId: '1:100144255999:android:e499037667acabe204cdca',
    messagingSenderId: '100144255999',
    projectId: 'justifind-9fda1',
    storageBucket: 'justifind-9fda1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH-oit5RpFkNWADB6MMmQZuZhh-gUq44E',
    appId: '1:100144255999:web:964c81d8f6fa0f4304cdca',
    messagingSenderId: '100144255999',
    projectId: 'justifind-9fda1',
    authDomain: 'justifind-9fda1.firebaseapp.com',
    storageBucket: 'justifind-9fda1.firebasestorage.app',
    measurementId: 'G-LKJRL74Y20',
  );
}
